apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-set
spec:
  generators:
  - list:
      elements:
      - cluster: development
      - cluster: production
  template:
    metadata:
      name: '{{cluster}}-test-set'
    spec:
      project: default
      source:
        repoURL: https://github.com/esgungor/argo-cd-appset
        targetRevision: HEAD
        path: post-test-api/overlays/{{cluster}}
